//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 12:32:19 PM CEST 
//

package eu.cumulus.certModelXML.certificate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TestCertificateType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TestCertificateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificateId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CertificationModelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CertificateInfo" type="{}certificateInfoType"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Toc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sProperty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "TestCertificateType", propOrder = { "certificateId",
		"certificationModelId", "certificateInfo", "status", "expirationDate",
		"toc", "sProperty" })
public class TestCertificateType {

	@XmlElement(name = "CertificateId")
	protected int certificateId;
	@XmlElement(name = "CertificationModelId", required = true)
	protected String certificationModelId;
	@XmlElement(name = "CertificateInfo", required = true)
	protected CertificateInfoType certificateInfo;
	@XmlElement(name = "Status", required = true)
	protected String status;
	@XmlElement(name = "ExpirationDate", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar expirationDate;
	@XmlElement(name = "Toc", required = true)
	protected TestCertificateType.Toc toc;
	@XmlElement(required = true)
	protected TestCertificateType.SProperty sProperty;

	/**
	 * Gets the value of the certificateId property.
	 * 
	 */
	public int getCertificateId() {
		return certificateId;
	}

	/**
	 * Sets the value of the certificateId property.
	 * 
	 */
	public void setCertificateId(int value) {
		this.certificateId = value;
	}

	/**
	 * Gets the value of the certificationModelId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCertificationModelId() {
		return certificationModelId;
	}

	/**
	 * Sets the value of the certificationModelId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCertificationModelId(String value) {
		this.certificationModelId = value;
	}

	/**
	 * Gets the value of the certificateInfo property.
	 * 
	 * @return possible object is {@link CertificateInfoType }
	 * 
	 */
	public CertificateInfoType getCertificateInfo() {
		return certificateInfo;
	}

	/**
	 * Sets the value of the certificateInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link CertificateInfoType }
	 * 
	 */
	public void setCertificateInfo(CertificateInfoType value) {
		this.certificateInfo = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the expirationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getExpirationDate() {
		return expirationDate;
	}

	/**
	 * Sets the value of the expirationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setExpirationDate(XMLGregorianCalendar value) {
		this.expirationDate = value;
	}

	/**
	 * Gets the value of the toc property.
	 * 
	 * @return possible object is {@link TestCertificateType.Toc }
	 * 
	 */
	public TestCertificateType.Toc getToc() {
		return toc;
	}

	/**
	 * Sets the value of the toc property.
	 * 
	 * @param value
	 *            allowed object is {@link TestCertificateType.Toc }
	 * 
	 */
	public void setToc(TestCertificateType.Toc value) {
		this.toc = value;
	}

	/**
	 * Gets the value of the sProperty property.
	 * 
	 * @return possible object is {@link TestCertificateType.SProperty }
	 * 
	 */
	public TestCertificateType.SProperty getSProperty() {
		return sProperty;
	}

	/**
	 * Sets the value of the sProperty property.
	 * 
	 * @param value
	 *            allowed object is {@link TestCertificateType.SProperty }
	 * 
	 */
	public void setSProperty(TestCertificateType.SProperty value) {
		this.sProperty = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class SProperty {

		@XmlAttribute(name = "class", required = true)
		@XmlSchemaType(name = "anyURI")
		protected String clazz;

		/**
		 * Gets the value of the clazz property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getClazz() {
			return clazz;
		}

		/**
		 * Sets the value of the clazz property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setClazz(String value) {
			this.clazz = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Toc {

		@XmlAttribute(required = true)
		protected String id;

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

	}

}
