//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:38:52 AM CEST 
//


package eu.cumulus.certModelXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for abstracCollectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstracCollectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Aggregator" type="{}aggregatorType"/>
 *         &lt;element name="TestCategory">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Functionality"/>
 *               &lt;enumeration value="Robustness"/>
 *               &lt;enumeration value="ResilienceToAttacks"/>
 *               &lt;enumeration value="PenetrationTest"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Actionability" type="{}actionabilityType" minOccurs="0"/>
 *         &lt;element name="Capability" type="{}capabilityType" minOccurs="0"/>
 *         &lt;element name="TestType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestGenerationModelLink" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="TestAttributes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="TestAttribute" type="{}testAttributeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TestCases">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="TestCase" type="{}testCaseType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstracCollectorType", propOrder = {
    "aggregator",
    "testCategory",
    "actionability",
    "capability",
    "testType",
    "testDescription",
    "testGenerationModelLink",
    "testAttributes",
    "testCases"
})
public class AbstracCollectorType {

    @XmlElement(name = "Aggregator", required = true)
    protected AggregatorType aggregator;
    @XmlElement(name = "TestCategory", required = true)
    protected String testCategory;
    @XmlElement(name = "Actionability")
    protected ActionabilityType actionability;
    @XmlElement(name = "Capability")
    protected CapabilityType capability;
    @XmlElement(name = "TestType", required = true)
    protected String testType;
    @XmlElement(name = "TestDescription", required = true)
    protected String testDescription;
    @XmlElement(name = "TestGenerationModelLink", required = true, defaultValue = "http://www.cumulus-project.eu")
    @XmlSchemaType(name = "anyURI")
    protected String testGenerationModelLink;
    @XmlElement(name = "TestAttributes", required = true)
    protected AbstracCollectorType.TestAttributes testAttributes;
    @XmlElement(name = "TestCases", required = true)
    protected AbstracCollectorType.TestCases testCases;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the aggregator property.
     * 
     * @return
     *     possible object is
     *     {@link AggregatorType }
     *     
     */
    public AggregatorType getAggregator() {
        return aggregator;
    }

    /**
     * Sets the value of the aggregator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregatorType }
     *     
     */
    public void setAggregator(AggregatorType value) {
        this.aggregator = value;
    }

    /**
     * Gets the value of the testCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCategory() {
        return testCategory;
    }

    /**
     * Sets the value of the testCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCategory(String value) {
        this.testCategory = value;
    }

    /**
     * Gets the value of the actionability property.
     * 
     * @return
     *     possible object is
     *     {@link ActionabilityType }
     *     
     */
    public ActionabilityType getActionability() {
        return actionability;
    }

    /**
     * Sets the value of the actionability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionabilityType }
     *     
     */
    public void setActionability(ActionabilityType value) {
        this.actionability = value;
    }

    /**
     * Gets the value of the capability property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityType }
     *     
     */
    public CapabilityType getCapability() {
        return capability;
    }

    /**
     * Sets the value of the capability property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityType }
     *     
     */
    public void setCapability(CapabilityType value) {
        this.capability = value;
    }

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the testDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestDescription() {
        return testDescription;
    }

    /**
     * Sets the value of the testDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestDescription(String value) {
        this.testDescription = value;
    }

    /**
     * Gets the value of the testGenerationModelLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestGenerationModelLink() {
        return testGenerationModelLink;
    }

    /**
     * Sets the value of the testGenerationModelLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestGenerationModelLink(String value) {
        this.testGenerationModelLink = value;
    }

    /**
     * Gets the value of the testAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AbstracCollectorType.TestAttributes }
     *     
     */
    public AbstracCollectorType.TestAttributes getTestAttributes() {
        return testAttributes;
    }

    /**
     * Sets the value of the testAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstracCollectorType.TestAttributes }
     *     
     */
    public void setTestAttributes(AbstracCollectorType.TestAttributes value) {
        this.testAttributes = value;
    }

    /**
     * Gets the value of the testCases property.
     * 
     * @return
     *     possible object is
     *     {@link AbstracCollectorType.TestCases }
     *     
     */
    public AbstracCollectorType.TestCases getTestCases() {
        return testCases;
    }

    /**
     * Sets the value of the testCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstracCollectorType.TestCases }
     *     
     */
    public void setTestCases(AbstracCollectorType.TestCases value) {
        this.testCases = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="TestAttribute" type="{}testAttributeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testAttribute"
    })
    public static class TestAttributes {

        @XmlElement(name = "TestAttribute", required = true)
        protected List<TestAttributeType> testAttribute;

        /**
         * Gets the value of the testAttribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testAttribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestAttribute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestAttributeType }
         * 
         * 
         */
        public List<TestAttributeType> getTestAttribute() {
            if (testAttribute == null) {
                testAttribute = new ArrayList<TestAttributeType>();
            }
            return this.testAttribute;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="TestCase" type="{}testCaseType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testCase"
    })
    public static class TestCases {

        @XmlElement(name = "TestCase", required = true)
        protected List<TestCaseType> testCase;

        /**
         * Gets the value of the testCase property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testCase property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestCase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestCaseType }
         * 
         * 
         */
        public List<TestCaseType> getTestCase() {
            if (testCase == null) {
                testCase = new ArrayList<TestCaseType>();
            }
            return this.testCase;
        }

    }

}
