//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for agentConfigurationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="agentConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="AgentURI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="AgentDesription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AgentIntegrityProtection" type="{}TC_IntegrityProtectionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AgentIsPresent" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agentConfigurationType", propOrder = { "agentURI",
		"agentDesription", "agentIntegrityProtection" })
public class AgentConfigurationType {

	@XmlElement(name = "AgentURI")
	@XmlSchemaType(name = "anyURI")
	protected String agentURI;
	@XmlElement(name = "AgentDesription")
	protected String agentDesription;
	@XmlElement(name = "AgentIntegrityProtection")
	protected TCIntegrityProtectionType agentIntegrityProtection;
	@XmlAttribute(name = "AgentIsPresent", required = true)
	protected boolean agentIsPresent;
	@XmlAttribute(name = "Id", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;

	/**
	 * Gets the value of the agentURI property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAgentURI() {
		return agentURI;
	}

	/**
	 * Sets the value of the agentURI property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAgentURI(String value) {
		this.agentURI = value;
	}

	/**
	 * Gets the value of the agentDesription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAgentDesription() {
		return agentDesription;
	}

	/**
	 * Sets the value of the agentDesription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAgentDesription(String value) {
		this.agentDesription = value;
	}

	/**
	 * Gets the value of the agentIntegrityProtection property.
	 * 
	 * @return possible object is {@link TCIntegrityProtectionType }
	 * 
	 */
	public TCIntegrityProtectionType getAgentIntegrityProtection() {
		return agentIntegrityProtection;
	}

	/**
	 * Sets the value of the agentIntegrityProtection property.
	 * 
	 * @param value
	 *            allowed object is {@link TCIntegrityProtectionType }
	 * 
	 */
	public void setAgentIntegrityProtection(TCIntegrityProtectionType value) {
		this.agentIntegrityProtection = value;
	}

	/**
	 * Gets the value of the agentIsPresent property.
	 * 
	 */
	public boolean isAgentIsPresent() {
		return agentIsPresent;
	}

	/**
	 * Sets the value of the agentIsPresent property.
	 * 
	 */
	public void setAgentIsPresent(boolean value) {
		this.agentIsPresent = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

}
