//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for capabilityType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="capabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="Attacker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttackName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttackerCapabilities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="CapabilityId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="AttackerCapability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "capabilityType", propOrder = { "attackerAndAttackNameAndAttackerCapabilities" })
public class CapabilityType {

	@XmlElementRefs({
			@XmlElementRef(name = "AttackName", type = JAXBElement.class),
			@XmlElementRef(name = "Attacker", type = JAXBElement.class),
			@XmlElementRef(name = "AttackerCapabilities", type = JAXBElement.class) })
	protected List<JAXBElement<?>> attackerAndAttackNameAndAttackerCapabilities;

	/**
	 * Gets the value of the attackerAndAttackNameAndAttackerCapabilities
	 * property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the
	 * attackerAndAttackNameAndAttackerCapabilities property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttackerAndAttackNameAndAttackerCapabilities().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link String }{@code >} {@link JAXBElement }
	 * {@code <}{@link CapabilityType.AttackerCapabilities }{@code >}
	 * {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<?>> getAttackerAndAttackNameAndAttackerCapabilities() {
		if (attackerAndAttackNameAndAttackerCapabilities == null) {
			attackerAndAttackNameAndAttackerCapabilities = new ArrayList<JAXBElement<?>>();
		}
		return this.attackerAndAttackNameAndAttackerCapabilities;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded">
	 *         &lt;element name="CapabilityId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
	 *         &lt;element name="AttackerCapability" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "capabilityIdAndAttackerCapability" })
	public static class AttackerCapabilities {

		@XmlElements({
				@XmlElement(name = "AttackerCapability", required = true, type = String.class),
				@XmlElement(name = "CapabilityId", required = true, type = BigInteger.class) })
		protected List<Serializable> capabilityIdAndAttackerCapability;

		/**
		 * Gets the value of the capabilityIdAndAttackerCapability property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the capabilityIdAndAttackerCapability
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getCapabilityIdAndAttackerCapability().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String } {@link BigInteger }
		 * 
		 * 
		 */
		public List<Serializable> getCapabilityIdAndAttackerCapability() {
			if (capabilityIdAndAttackerCapability == null) {
				capabilityIdAndAttackerCapability = new ArrayList<Serializable>();
			}
			return this.capabilityIdAndAttackerCapability;
		}

	}

}
