//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:38:52 AM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for conditionForSomministrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionForSomministrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ThresholdTraffic" type="{}thresholdTrafficType"/>
 *         &lt;element name="Event" type="{}eventType"/>
 *         &lt;element name="OtherCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeltaTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionForSomministrationType", propOrder = {
    "thresholdTraffic",
    "event",
    "otherCondition",
    "deltaTime"
})
public class ConditionForSomministrationType {

    @XmlElement(name = "ThresholdTraffic")
    protected ThresholdTrafficType thresholdTraffic;
    @XmlElement(name = "Event")
    protected EventType event;
    @XmlElement(name = "OtherCondition")
    protected String otherCondition;
    @XmlElement(name = "DeltaTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar deltaTime;

    /**
     * Gets the value of the thresholdTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link ThresholdTrafficType }
     *     
     */
    public ThresholdTrafficType getThresholdTraffic() {
        return thresholdTraffic;
    }

    /**
     * Sets the value of the thresholdTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThresholdTrafficType }
     *     
     */
    public void setThresholdTraffic(ThresholdTrafficType value) {
        this.thresholdTraffic = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setEvent(EventType value) {
        this.event = value;
    }

    /**
     * Gets the value of the otherCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCondition() {
        return otherCondition;
    }

    /**
     * Sets the value of the otherCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCondition(String value) {
        this.otherCondition = value;
    }

    /**
     * Gets the value of the deltaTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeltaTime() {
        return deltaTime;
    }

    /**
     * Sets the value of the deltaTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeltaTime(XMLGregorianCalendar value) {
        this.deltaTime = value;
    }

}
