//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for elementForExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementForExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="TestingTool" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Others" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementForExtensionType", propOrder = {
    "environment",
    "testingTool",
    "code",
    "others"
})
public class ElementForExtensionType {

    @XmlElement(name = "Environment", required = true)
    protected Object environment;
    @XmlElement(name = "TestingTool", required = true)
    protected Object testingTool;
    @XmlElement(name = "Code", required = true)
    protected Object code;
    @XmlElement(name = "Others", required = true)
    protected Object others;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEnvironment(Object value) {
        this.environment = value;
    }

    /**
     * Gets the value of the testingTool property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTestingTool() {
        return testingTool;
    }

    /**
     * Sets the value of the testingTool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTestingTool(Object value) {
        this.testingTool = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCode(Object value) {
        this.code = value;
    }

    /**
     * Gets the value of the others property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOthers() {
        return others;
    }

    /**
     * Sets the value of the others property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOthers(Object value) {
        this.others = value;
    }

}
