//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for GeneralCollectorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralCollectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgentURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ConditionForSomministration" type="{}conditionForSomministrationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AbstractCollector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ExpirationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" />
 *       &lt;attribute name="Descriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="isStatic" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="toDeploy" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralCollectorType", propOrder = { "agentURI",
		"conditionForSomministration", "abstractCollector" })
public class GeneralCollectorType {

	@XmlElement(name = "AgentURI")
	@XmlSchemaType(name = "anyURI")
	protected List<String> agentURI;
	@XmlElement(name = "ConditionForSomministration")
	protected List<ConditionForSomministrationType> conditionForSomministration;
	@XmlElement(name = "AbstractCollector", required = true)
	protected String abstractCollector;
	@XmlAttribute(name = "ExpirationTime", required = true)
	@XmlSchemaType(name = "gYearMonth")
	protected XMLGregorianCalendar expirationTime;
	@XmlAttribute(name = "Descriptor")
	protected String descriptor;
	@XmlAttribute(name = "Id")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;
	@XmlAttribute
	protected Boolean isStatic;
	@XmlAttribute
	protected Boolean toDeploy;

	/**
	 * Gets the value of the agentURI property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the agentURI property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAgentURI().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getAgentURI() {
		if (agentURI == null) {
			agentURI = new ArrayList<String>();
		}
		return this.agentURI;
	}

	/**
	 * Gets the value of the conditionForSomministration property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the conditionForSomministration property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getConditionForSomministration().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ConditionForSomministrationType }
	 * 
	 * 
	 */
	public List<ConditionForSomministrationType> getConditionForSomministration() {
		if (conditionForSomministration == null) {
			conditionForSomministration = new ArrayList<ConditionForSomministrationType>();
		}
		return this.conditionForSomministration;
	}

	/**
	 * Gets the value of the abstractCollector property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAbstractCollector() {
		return abstractCollector;
	}

	/**
	 * Sets the value of the abstractCollector property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAbstractCollector(String value) {
		this.abstractCollector = value;
	}

	/**
	 * Gets the value of the expirationTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getExpirationTime() {
		return expirationTime;
	}

	/**
	 * Sets the value of the expirationTime property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setExpirationTime(XMLGregorianCalendar value) {
		this.expirationTime = value;
	}

	/**
	 * Gets the value of the descriptor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescriptor() {
		return descriptor;
	}

	/**
	 * Sets the value of the descriptor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescriptor(String value) {
		this.descriptor = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the isStatic property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIsStatic() {
		return isStatic;
	}

	/**
	 * Sets the value of the isStatic property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsStatic(Boolean value) {
		this.isStatic = value;
	}

	/**
	 * Gets the value of the toDeploy property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isToDeploy() {
		return toDeploy;
	}

	/**
	 * Sets the value of the toDeploy property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setToDeploy(Boolean value) {
		this.toDeploy = value;
	}

}
