//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifeCycleStates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LifeCycleStates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="singleState" type="{}SingleLifeState"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NumberOfStates" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifeCycleStates", propOrder = {
    "singleState"
})
public class LifeCycleStates {

    @XmlElement(required = true)
    protected List<SingleLifeState> singleState;
    @XmlAttribute(name = "NumberOfStates", required = true)
    protected BigInteger numberOfStates;

    /**
     * Gets the value of the singleState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleLifeState }
     * 
     * 
     */
    public List<SingleLifeState> getSingleState() {
        if (singleState == null) {
            singleState = new ArrayList<SingleLifeState>();
        }
        return this.singleState;
    }

    /**
     * Gets the value of the numberOfStates property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfStates() {
        return numberOfStates;
    }

    /**
     * Sets the value of the numberOfStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfStates(BigInteger value) {
        this.numberOfStates = value;
    }

}
