//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for lifeCycleStateType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lifeCycleStateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LifeCycleTransition" type="{}lifeCycleTransitionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LifeCycle" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="LifeCycleStateName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NOT_ISSUED"/>
 *             &lt;enumeration value="ISSUED"/>
 *             &lt;enumeration value="SUSPENDED"/>
 *             &lt;enumeration value="REVOCKED"/>
 *             &lt;enumeration value="EXPIRED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lifeCycleStateType", propOrder = { "lifeCycleTransition" })
public class LifeCycleStateType {

	@XmlElement(name = "LifeCycleTransition", required = true)
	protected LifeCycleTransitionType lifeCycleTransition;
	@XmlAttribute(name = "LifeCycle")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String lifeCycle;
	@XmlAttribute(name = "LifeCycleStateName")
	protected String lifeCycleStateName;

	/**
	 * Gets the value of the lifeCycleTransition property.
	 * 
	 * @return possible object is {@link LifeCycleTransitionType }
	 * 
	 */
	public LifeCycleTransitionType getLifeCycleTransition() {
		return lifeCycleTransition;
	}

	/**
	 * Sets the value of the lifeCycleTransition property.
	 * 
	 * @param value
	 *            allowed object is {@link LifeCycleTransitionType }
	 * 
	 */
	public void setLifeCycleTransition(LifeCycleTransitionType value) {
		this.lifeCycleTransition = value;
	}

	/**
	 * Gets the value of the lifeCycle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLifeCycle() {
		return lifeCycle;
	}

	/**
	 * Sets the value of the lifeCycle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLifeCycle(String value) {
		this.lifeCycle = value;
	}

	/**
	 * Gets the value of the lifeCycleStateName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLifeCycleStateName() {
		return lifeCycleStateName;
	}

	/**
	 * Sets the value of the lifeCycleStateName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLifeCycleStateName(String value) {
		this.lifeCycleStateName = value;
	}

}
