//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:38:52 AM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lifeCycleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lifeCycleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LifeCycleStates" type="{}LifeCycleStates"/>
 *       &lt;/sequence>
 *       &lt;attribute name="InitialState" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="NOT_ISSUED" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lifeCycleType", propOrder = {
    "lifeCycleStates"
})
public class LifeCycleType {

    @XmlElement(name = "LifeCycleStates", required = true)
    protected LifeCycleStates lifeCycleStates;
    @XmlAttribute(name = "InitialState", required = true)
    protected String initialState;

    /**
     * Gets the value of the lifeCycleStates property.
     * 
     * @return
     *     possible object is
     *     {@link LifeCycleStates }
     *     
     */
    public LifeCycleStates getLifeCycleStates() {
        return lifeCycleStates;
    }

    /**
     * Sets the value of the lifeCycleStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeCycleStates }
     *     
     */
    public void setLifeCycleStates(LifeCycleStates value) {
        this.lifeCycleStates = value;
    }

    /**
     * Gets the value of the initialState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialState() {
        if (initialState == null) {
            return "NOT_ISSUED";
        } else {
            return initialState;
        }
    }

    /**
     * Sets the value of the initialState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialState(String value) {
        this.initialState = value;
    }

}
