//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:38:52 AM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lifeCycleTransitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lifeCycleTransitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromState">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NOT_ISSUED"/>
 *               &lt;enumeration value="ISSUED"/>
 *               &lt;enumeration value="SUSPENDED"/>
 *               &lt;enumeration value="REVOKED"/>
 *               &lt;enumeration value="EXPIRED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ToState">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NOT_ISSUED"/>
 *               &lt;enumeration value="ISSUED"/>
 *               &lt;enumeration value="SUSPENDED"/>
 *               &lt;enumeration value="REVOKED"/>
 *               &lt;enumeration value="EXPIRED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConditionForLifeCycleTransition" type="{}lifeCycleConditionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lifeCycleTransitionType", propOrder = {
    "fromState",
    "toState",
    "conditionForLifeCycleTransition"
})
public class LifeCycleTransitionType {

    @XmlElement(name = "FromState", required = true)
    protected String fromState;
    @XmlElement(name = "ToState", required = true)
    protected String toState;
    @XmlElement(name = "ConditionForLifeCycleTransition", required = true)
    protected LifeCycleConditionType conditionForLifeCycleTransition;

    /**
     * Gets the value of the fromState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromState() {
        return fromState;
    }

    /**
     * Sets the value of the fromState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromState(String value) {
        this.fromState = value;
    }

    /**
     * Gets the value of the toState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToState() {
        return toState;
    }

    /**
     * Sets the value of the toState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToState(String value) {
        this.toState = value;
    }

    /**
     * Gets the value of the conditionForLifeCycleTransition property.
     * 
     * @return
     *     possible object is
     *     {@link LifeCycleConditionType }
     *     
     */
    public LifeCycleConditionType getConditionForLifeCycleTransition() {
        return conditionForLifeCycleTransition;
    }

    /**
     * Sets the value of the conditionForLifeCycleTransition property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeCycleConditionType }
     *     
     */
    public void setConditionForLifeCycleTransition(LifeCycleConditionType value) {
        this.conditionForLifeCycleTransition = value;
    }

}
