//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lifeCycleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lifeCycleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LifeCycleStates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="LifeCycleId" type="{http://www.w3.org/2001/XMLSchema}ID"/>
 *                   &lt;element name="LifeCycleState">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="NOT_ISSUED"/>
 *                         &lt;enumeration value="ISSUED"/>
 *                         &lt;enumeration value="SUSPENDED"/>
 *                         &lt;enumeration value="REVOKED"/>
 *                         &lt;enumeration value="EXPIRED"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LifeCycleTransitions">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="lifeCycleTransition" type="{}lifeCycleTransitionType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="NumberOfStates" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="InitialState" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="NOT_ISSUED" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lifeCycleType", propOrder = { "lifeCycleStates" })
public class LifeCycleType {

	@XmlElement(name = "LifeCycleStates", required = true)
	protected LifeCycleType.LifeCycleStates lifeCycleStates;
	@XmlAttribute(name = "InitialState", required = true)
	protected String initialState;

	/**
	 * Gets the value of the lifeCycleStates property.
	 * 
	 * @return possible object is {@link LifeCycleType.LifeCycleStates }
	 * 
	 */
	public LifeCycleType.LifeCycleStates getLifeCycleStates() {
		return lifeCycleStates;
	}

	/**
	 * Sets the value of the lifeCycleStates property.
	 * 
	 * @param value
	 *            allowed object is {@link LifeCycleType.LifeCycleStates }
	 * 
	 */
	public void setLifeCycleStates(LifeCycleType.LifeCycleStates value) {
		this.lifeCycleStates = value;
	}

	/**
	 * Gets the value of the initialState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInitialState() {
		if (initialState == null) {
			return "NOT_ISSUED";
		} else {
			return initialState;
		}
	}

	/**
	 * Sets the value of the initialState property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInitialState(String value) {
		this.initialState = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded">
	 *         &lt;element name="LifeCycleId" type="{http://www.w3.org/2001/XMLSchema}ID"/>
	 *         &lt;element name="LifeCycleState">
	 *           &lt;simpleType>
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *               &lt;enumeration value="NOT_ISSUED"/>
	 *               &lt;enumeration value="ISSUED"/>
	 *               &lt;enumeration value="SUSPENDED"/>
	 *               &lt;enumeration value="REVOKED"/>
	 *               &lt;enumeration value="EXPIRED"/>
	 *             &lt;/restriction>
	 *           &lt;/simpleType>
	 *         &lt;/element>
	 *         &lt;element name="LifeCycleTransitions">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence maxOccurs="unbounded">
	 *                   &lt;element name="lifeCycleTransition" type="{}lifeCycleTransitionType"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="NumberOfStates" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions" })
	public static class LifeCycleStates {

		@XmlElementRefs({
				@XmlElementRef(name = "LifeCycleId", type = JAXBElement.class),
				@XmlElementRef(name = "LifeCycleState", type = JAXBElement.class),
				@XmlElementRef(name = "LifeCycleTransitions", type = JAXBElement.class) })
		protected List<JAXBElement<?>> lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions;
		@XmlAttribute(name = "NumberOfStates", required = true)
		protected BigInteger numberOfStates;

		/**
		 * Gets the value of the
		 * lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the
		 * lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getLifeCycleIdAndLifeCycleStateAndLifeCycleTransitions().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link JAXBElement }{@code <}
		 * {@link LifeCycleType.LifeCycleStates.LifeCycleTransitions }{@code >}
		 * {@link JAXBElement }{@code <}{@link String }{@code >}
		 * {@link JAXBElement }{@code <}{@link String }{@code >}
		 * 
		 * 
		 */
		public List<JAXBElement<?>> getLifeCycleIdAndLifeCycleStateAndLifeCycleTransitions() {
			if (lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions == null) {
				lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions = new ArrayList<JAXBElement<?>>();
			}
			return this.lifeCycleIdAndLifeCycleStateAndLifeCycleTransitions;
		}

		/**
		 * Gets the value of the numberOfStates property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getNumberOfStates() {
			return numberOfStates;
		}

		/**
		 * Sets the value of the numberOfStates property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setNumberOfStates(BigInteger value) {
			this.numberOfStates = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence maxOccurs="unbounded">
		 *         &lt;element name="lifeCycleTransition" type="{}lifeCycleTransitionType"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "lifeCycleTransition" })
		public static class LifeCycleTransitions {

			@XmlElement(required = true)
			protected List<LifeCycleTransitionType> lifeCycleTransition;

			/**
			 * Gets the value of the lifeCycleTransition property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the lifeCycleTransition
			 * property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getLifeCycleTransition().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link LifeCycleTransitionType }
			 * 
			 * 
			 */
			public List<LifeCycleTransitionType> getLifeCycleTransition() {
				if (lifeCycleTransition == null) {
					lifeCycleTransition = new ArrayList<LifeCycleTransitionType>();
				}
				return this.lifeCycleTransition;
			}

		}

	}

}
