//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operativeConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operativeConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TocTechnicalSpecifications" type="{}tocTechSpecType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operativeConditionsType", propOrder = {
    "tocTechnicalSpecifications"
})
public class OperativeConditionsType {

    @XmlElement(name = "TocTechnicalSpecifications", required = true)
    protected TocTechSpecType tocTechnicalSpecifications;

    /**
     * Gets the value of the tocTechnicalSpecifications property.
     * 
     * @return
     *     possible object is
     *     {@link TocTechSpecType }
     *     
     */
    public TocTechSpecType getTocTechnicalSpecifications() {
        return tocTechnicalSpecifications;
    }

    /**
     * Sets the value of the tocTechnicalSpecifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocTechSpecType }
     *     
     */
    public void setTocTechnicalSpecifications(TocTechSpecType value) {
        this.tocTechnicalSpecifications = value;
    }

}
