//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for securityPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securityPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sProperty" type="{}propertyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SecurityPropertyId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SecurityPropertyDefinition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Vocabulary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityPropertyType", propOrder = {
    "sProperty"
})
public class SecurityPropertyType {

    @XmlElement(required = true)
    protected PropertyType sProperty;
    @XmlAttribute(name = "SecurityPropertyId", required = true)
    protected String securityPropertyId;
    @XmlAttribute(name = "SecurityPropertyDefinition", required = true)
    protected String securityPropertyDefinition;
    @XmlAttribute(name = "Vocabulary")
    protected String vocabulary;
    @XmlAttribute(name = "ShortName")
    protected String shortName;

    /**
     * Gets the value of the sProperty property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyType }
     *     
     */
    public PropertyType getSProperty() {
        return sProperty;
    }

    /**
     * Sets the value of the sProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyType }
     *     
     */
    public void setSProperty(PropertyType value) {
        this.sProperty = value;
    }

    /**
     * Gets the value of the securityPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPropertyId() {
        return securityPropertyId;
    }

    /**
     * Sets the value of the securityPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPropertyId(String value) {
        this.securityPropertyId = value;
    }

    /**
     * Gets the value of the securityPropertyDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPropertyDefinition() {
        return securityPropertyDefinition;
    }

    /**
     * Sets the value of the securityPropertyDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPropertyDefinition(String value) {
        this.securityPropertyDefinition = value;
    }

    /**
     * Gets the value of the vocabulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabulary() {
        return vocabulary;
    }

    /**
     * Sets the value of the vocabulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabulary(String value) {
        this.vocabulary = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

}
