//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SingleLifeState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleLifeState">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LifeCycleState">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NOT_ISSUED"/>
 *               &lt;enumeration value="ISSUED"/>
 *               &lt;enumeration value="SUSPENDED"/>
 *               &lt;enumeration value="REVOKED"/>
 *               &lt;enumeration value="EXPIRED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LifeCycleId" type="{http://www.w3.org/2001/XMLSchema}ID"/>
 *         &lt;element name="LifeCycleTransitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="lifeCycleTransition" type="{}lifeCycleTransitionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleLifeState", propOrder = {
    "lifeCycleState",
    "lifeCycleId",
    "lifeCycleTransitions"
})
public class SingleLifeState {

    @XmlElement(name = "LifeCycleState", required = true)
    protected String lifeCycleState;
    @XmlElement(name = "LifeCycleId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String lifeCycleId;
    @XmlElement(name = "LifeCycleTransitions", required = true)
    protected SingleLifeState.LifeCycleTransitions lifeCycleTransitions;

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifeCycleState(String value) {
        this.lifeCycleState = value;
    }

    /**
     * Gets the value of the lifeCycleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifeCycleId() {
        return lifeCycleId;
    }

    /**
     * Sets the value of the lifeCycleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifeCycleId(String value) {
        this.lifeCycleId = value;
    }

    /**
     * Gets the value of the lifeCycleTransitions property.
     * 
     * @return
     *     possible object is
     *     {@link SingleLifeState.LifeCycleTransitions }
     *     
     */
    public SingleLifeState.LifeCycleTransitions getLifeCycleTransitions() {
        return lifeCycleTransitions;
    }

    /**
     * Sets the value of the lifeCycleTransitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleLifeState.LifeCycleTransitions }
     *     
     */
    public void setLifeCycleTransitions(SingleLifeState.LifeCycleTransitions value) {
        this.lifeCycleTransitions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="lifeCycleTransition" type="{}lifeCycleTransitionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lifeCycleTransition"
    })
    public static class LifeCycleTransitions {

        @XmlElement(required = true)
        protected List<LifeCycleTransitionType> lifeCycleTransition;

        /**
         * Gets the value of the lifeCycleTransition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lifeCycleTransition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLifeCycleTransition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LifeCycleTransitionType }
         * 
         * 
         */
        public List<LifeCycleTransitionType> getLifeCycleTransition() {
            if (lifeCycleTransition == null) {
                lifeCycleTransition = new ArrayList<LifeCycleTransitionType>();
            }
            return this.lifeCycleTransition;
        }

    }

}
