//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for testerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="testerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TesterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TesterRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testerType", propOrder = { "testerName", "testerRole" })
public class TesterType {

	@XmlElement(name = "TesterName", required = true)
	protected String testerName;
	@XmlElement(name = "TesterRole", required = true)
	protected String testerRole;

	/**
	 * Gets the value of the testerName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTesterName() {
		return testerName;
	}

	/**
	 * Sets the value of the testerName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTesterName(String value) {
		this.testerName = value;
	}

	/**
	 * Gets the value of the testerRole property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTesterRole() {
		return testerRole;
	}

	/**
	 * Sets the value of the testerRole property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTesterRole(String value) {
		this.testerRole = value;
	}

}
