//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testBasedCertificationModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testBasedCertificationModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificationModelId" type="{}certificationModelType"/>
 *         &lt;element name="Collectors" type="{}collectorType"/>
 *         &lt;element name="LifeCycle" type="{}lifeCycleType"/>
 *         &lt;element name="Toc" type="{}tocType"/>
 *         &lt;element name="TestedSecurityProperty" type="{}securityPropertyType"/>
 *         &lt;element name="Tester" type="{}testerType"/>
 *         &lt;element name="Context" type="{}contextType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "testBasedCertificationModelType", propOrder = {
    "certificationModelId",
    "collectors",
    "lifeCycle",
    "toc",
    "testedSecurityProperty",
    "tester",
    "context"
})
public class TestBasedCertificationModelType {

    @XmlElement(name = "CertificationModelId", required = true)
    protected CertificationModelType certificationModelId;
    @XmlElement(name = "Collectors", required = true)
    protected CollectorType collectors;
    @XmlElement(name = "LifeCycle", required = true)
    protected LifeCycleType lifeCycle;
    @XmlElement(name = "Toc", required = true)
    protected TocType toc;
    @XmlElement(name = "TestedSecurityProperty", required = true)
    protected SecurityPropertyType testedSecurityProperty;
    @XmlElement(name = "Tester", required = true)
    protected TesterType tester;
    @XmlElement(name = "Context", required = true)
    protected ContextType context;

    /**
     * Gets the value of the certificationModelId property.
     * 
     * @return
     *     possible object is
     *     {@link CertificationModelType }
     *     
     */
    public CertificationModelType getCertificationModelId() {
        return certificationModelId;
    }

    /**
     * Sets the value of the certificationModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificationModelType }
     *     
     */
    public void setCertificationModelId(CertificationModelType value) {
        this.certificationModelId = value;
    }

    /**
     * Gets the value of the collectors property.
     * 
     * @return
     *     possible object is
     *     {@link CollectorType }
     *     
     */
    public CollectorType getCollectors() {
        return collectors;
    }

    /**
     * Sets the value of the collectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectorType }
     *     
     */
    public void setCollectors(CollectorType value) {
        this.collectors = value;
    }

    /**
     * Gets the value of the lifeCycle property.
     * 
     * @return
     *     possible object is
     *     {@link LifeCycleType }
     *     
     */
    public LifeCycleType getLifeCycle() {
        return lifeCycle;
    }

    /**
     * Sets the value of the lifeCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeCycleType }
     *     
     */
    public void setLifeCycle(LifeCycleType value) {
        this.lifeCycle = value;
    }

    /**
     * Gets the value of the toc property.
     * 
     * @return
     *     possible object is
     *     {@link TocType }
     *     
     */
    public TocType getToc() {
        return toc;
    }

    /**
     * Sets the value of the toc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocType }
     *     
     */
    public void setToc(TocType value) {
        this.toc = value;
    }

    /**
     * Gets the value of the testedSecurityProperty property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityPropertyType }
     *     
     */
    public SecurityPropertyType getTestedSecurityProperty() {
        return testedSecurityProperty;
    }

    /**
     * Sets the value of the testedSecurityProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityPropertyType }
     *     
     */
    public void setTestedSecurityProperty(SecurityPropertyType value) {
        this.testedSecurityProperty = value;
    }

    /**
     * Gets the value of the tester property.
     * 
     * @return
     *     possible object is
     *     {@link TesterType }
     *     
     */
    public TesterType getTester() {
        return tester;
    }

    /**
     * Sets the value of the tester property.
     * 
     * @param value
     *     allowed object is
     *     {@link TesterType }
     *     
     */
    public void setTester(TesterType value) {
        this.tester = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link ContextType }
     *     
     */
    public ContextType getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextType }
     *     
     */
    public void setContext(ContextType value) {
        this.context = value;
    }

}
