//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:38:52 AM CEST 
//


package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testMetricsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testMetricsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OperationCoverage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="InputPartitionCoverage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="BranchCoverage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ConditionCoverage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="PathCoverage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttackCoverage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testMetricsType", propOrder = {
    "operationCoverage",
    "inputPartitionCoverage",
    "branchCoverage",
    "conditionCoverage",
    "pathCoverage",
    "attackCoverage",
    "other"
})
public class TestMetricsType {

    @XmlElement(name = "OperationCoverage", required = true)
    protected Object operationCoverage;
    @XmlElement(name = "InputPartitionCoverage", required = true)
    protected Object inputPartitionCoverage;
    @XmlElement(name = "BranchCoverage", required = true)
    protected Object branchCoverage;
    @XmlElement(name = "ConditionCoverage", required = true)
    protected Object conditionCoverage;
    @XmlElement(name = "PathCoverage", required = true)
    protected String pathCoverage;
    @XmlElement(name = "AttackCoverage", required = true)
    protected Object attackCoverage;
    @XmlElement(name = "Other", required = true)
    protected Object other;

    /**
     * Gets the value of the operationCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOperationCoverage() {
        return operationCoverage;
    }

    /**
     * Sets the value of the operationCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOperationCoverage(Object value) {
        this.operationCoverage = value;
    }

    /**
     * Gets the value of the inputPartitionCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInputPartitionCoverage() {
        return inputPartitionCoverage;
    }

    /**
     * Sets the value of the inputPartitionCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInputPartitionCoverage(Object value) {
        this.inputPartitionCoverage = value;
    }

    /**
     * Gets the value of the branchCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBranchCoverage() {
        return branchCoverage;
    }

    /**
     * Sets the value of the branchCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBranchCoverage(Object value) {
        this.branchCoverage = value;
    }

    /**
     * Gets the value of the conditionCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConditionCoverage() {
        return conditionCoverage;
    }

    /**
     * Sets the value of the conditionCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConditionCoverage(Object value) {
        this.conditionCoverage = value;
    }

    /**
     * Gets the value of the pathCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathCoverage() {
        return pathCoverage;
    }

    /**
     * Sets the value of the pathCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathCoverage(String value) {
        this.pathCoverage = value;
    }

    /**
     * Gets the value of the attackCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAttackCoverage() {
        return attackCoverage;
    }

    /**
     * Sets the value of the attackCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAttackCoverage(Object value) {
        this.attackCoverage = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOther(Object value) {
        this.other = value;
    }

}
