//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:07:54 PM CEST 
//

package eu.cumulus.certModelXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for thresholdTrafficType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="thresholdTrafficType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TrafficType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ThresholdUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ThresholdValue" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "thresholdTrafficType")
public class ThresholdTrafficType {

	@XmlAttribute(name = "TrafficType", required = true)
	protected String trafficType;
	@XmlAttribute(name = "ThresholdUnit", required = true)
	protected String thresholdUnit;
	@XmlAttribute(name = "ThresholdValue", required = true)
	protected float thresholdValue;

	/**
	 * Gets the value of the trafficType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTrafficType() {
		return trafficType;
	}

	/**
	 * Sets the value of the trafficType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTrafficType(String value) {
		this.trafficType = value;
	}

	/**
	 * Gets the value of the thresholdUnit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getThresholdUnit() {
		return thresholdUnit;
	}

	/**
	 * Sets the value of the thresholdUnit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setThresholdUnit(String value) {
		this.thresholdUnit = value;
	}

	/**
	 * Gets the value of the thresholdValue property.
	 * 
	 */
	public float getThresholdValue() {
		return thresholdValue;
	}

	/**
	 * Sets the value of the thresholdValue property.
	 * 
	 */
	public void setThresholdValue(float value) {
		this.thresholdValue = value;
	}

}
