//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:56:53 PM CEST 
//


package eu.cumulus.certModelXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tocType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CloudLayer" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SaaS"/>
 *               &lt;enumeration value="PaaS"/>
 *               &lt;enumeration value="IaaS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConcreteToc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TocDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="WS"/>
 *               &lt;enumeration value="Application"/>
 *               &lt;enumeration value="DBMS"/>
 *               &lt;enumeration value="WEBSERVER"/>
 *               &lt;enumeration value="EMAIL"/>
 *               &lt;enumeration value="CRM"/>
 *               &lt;enumeration value="SDK"/>
 *               &lt;enumeration value="VIRTUALMACHINE"/>
 *               &lt;enumeration value="HD"/>
 *               &lt;enumeration value="SWITCH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TocURI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="ToTs" type="{}targetOfTestsType"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element name="OperativeCondition" type="{}operativeConditionsType"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tocType", propOrder = {
    "cloudLayer",
    "concreteToc",
    "tocDescription",
    "tocURI",
    "toTs",
    "operativeCondition"
})
public class TocType {

    @XmlElement(name = "CloudLayer", required = true)
    protected List<String> cloudLayer;
    @XmlElement(name = "ConcreteToc", required = true)
    protected String concreteToc;
    @XmlElement(name = "TocDescription", required = true)
    protected String tocDescription;
    @XmlElement(name = "TocURI", required = true, defaultValue = "http://www.cumulus-project.eu")
    @XmlSchemaType(name = "anyURI")
    protected String tocURI;
    @XmlElement(name = "ToTs", required = true)
    protected TargetOfTestsType toTs;
    @XmlElement(name = "OperativeCondition", required = true)
    protected List<OperativeConditionsType> operativeCondition;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the cloudLayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloudLayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloudLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCloudLayer() {
        if (cloudLayer == null) {
            cloudLayer = new ArrayList<String>();
        }
        return this.cloudLayer;
    }

    /**
     * Gets the value of the concreteToc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcreteToc() {
        return concreteToc;
    }

    /**
     * Sets the value of the concreteToc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcreteToc(String value) {
        this.concreteToc = value;
    }

    /**
     * Gets the value of the tocDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTocDescription() {
        return tocDescription;
    }

    /**
     * Sets the value of the tocDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTocDescription(String value) {
        this.tocDescription = value;
    }

    /**
     * Gets the value of the tocURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTocURI() {
        return tocURI;
    }

    /**
     * Sets the value of the tocURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTocURI(String value) {
        this.tocURI = value;
    }

    /**
     * Gets the value of the toTs property.
     * 
     * @return
     *     possible object is
     *     {@link TargetOfTestsType }
     *     
     */
    public TargetOfTestsType getToTs() {
        return toTs;
    }

    /**
     * Sets the value of the toTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetOfTestsType }
     *     
     */
    public void setToTs(TargetOfTestsType value) {
        this.toTs = value;
    }

    /**
     * Gets the value of the operativeCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operativeCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperativeCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperativeConditionsType }
     * 
     * 
     */
    public List<OperativeConditionsType> getOperativeCondition() {
        if (operativeCondition == null) {
            operativeCondition = new ArrayList<OperativeConditionsType>();
        }
        return this.operativeCondition;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
