//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.12 at 05:09:06 PM CET 
//


package eu.cumulus.agentMessageXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Preconditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HiddenCommunications" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Input" type="{}InputType"/>
 *         &lt;element name="ExpectedOutput" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Operation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestInstanceType", propOrder = {
    "preconditions",
    "hiddenCommunications",
    "input",
    "expectedOutput",
    "postConditions"
})
public class TestInstanceType {

    @XmlElement(name = "Preconditions", required = true)
    protected String preconditions;
    @XmlElement(name = "HiddenCommunications", required = true)
    protected String hiddenCommunications;
    @XmlElement(name = "Input", required = true)
    protected InputType input;
    @XmlElement(name = "ExpectedOutput", required = true)
    protected String expectedOutput;
    @XmlElement(name = "PostConditions", required = true)
    protected String postConditions;
    @XmlAttribute(name = "Operation", required = true)
    protected String operation;

    /**
     * Gets the value of the preconditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreconditions() {
        return preconditions;
    }

    /**
     * Sets the value of the preconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreconditions(String value) {
        this.preconditions = value;
    }

    /**
     * Gets the value of the hiddenCommunications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHiddenCommunications() {
        return hiddenCommunications;
    }

    /**
     * Sets the value of the hiddenCommunications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHiddenCommunications(String value) {
        this.hiddenCommunications = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link InputType }
     *     
     */
    public InputType getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputType }
     *     
     */
    public void setInput(InputType value) {
        this.input = value;
    }

    /**
     * Gets the value of the expectedOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedOutput() {
        return expectedOutput;
    }

    /**
     * Sets the value of the expectedOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedOutput(String value) {
        this.expectedOutput = value;
    }

    /**
     * Gets the value of the postConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostConditions() {
        return postConditions;
    }

    /**
     * Sets the value of the postConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostConditions(String value) {
        this.postConditions = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

}
