<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://DefaultNamespace" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://DefaultNamespace" xmlns:intf="http://DefaultNamespace" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://DefaultNamespace" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getSperanza">
    <complexType/>
   </element>
   <element name="getSperanzaResponse">
    <complexType>
     <sequence>
      <element name="getSperanzaReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getSperanzaRequest">

      <wsdl:part element="impl:getSperanza" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getSperanzaResponse">

      <wsdl:part element="impl:getSperanzaResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="CiaoMondo">

      <wsdl:operation name="getSperanza">

         <wsdl:input message="impl:getSperanzaRequest" name="getSperanzaRequest">

       </wsdl:input>

         <wsdl:output message="impl:getSperanzaResponse" name="getSperanzaResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="CiaoMondoSoapBinding" type="impl:CiaoMondo">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getSperanza">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getSperanzaRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getSperanzaResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="CiaoMondoService">

      <wsdl:port binding="impl:CiaoMondoSoapBinding" name="CiaoMondo">

         <wsdlsoap:address location="http://localhost:8080/AxisTest/services/CiaoMondo"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
